name: 编译 "apollolake-7.0.1-42218"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 同步仓库
        uses: actions/checkout@v2

      - name: 构建工具链
        run: |
          sudo chmod +x rp-helper.sh
          ./rp-helper.sh build apollolake-7.0.1-42218

      - name: 添加扩展驱动
        run: |
          ./rploader.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/develop/redpill-acpid/rpext-index.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/develop/redpill-virtio/rpext-index.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://github.com/RedPill-TTG/redpill-boot-wait/raw/master/recipes/universal.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://github.com/RedPill-TTG/redpill-virtio/raw/master/recipes/ds918p_41890.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8169/rpext-index.json
          ./rploader.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8169/releases/ds918p_42218.json

      - name: 编译引导镜像
        run: ./rp-helper.sh auto apollolake-7.0.1-42218

      - name: 清理并构建缓存
        run: ./rp-helper.sh clean apollolake-7.0.1-42218

      - name: 上传镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-apollolake-7.0.1-42218
          path: images/redpill-DS[39]*.img
          if-no-files-found: error
